<a href="https://colab.research.google.com/github/MrPokko/MachineLearning_Ganjil/blob/main/Copy_of_ML_Modul_9_Week_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Praktikum 4 - Klasifikasi dengan ANN**

In [1]:
!pip install tensorflow

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
ann = tf.keras.models.Sequential()

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5913 - accuracy: 0.7195
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4764 - accuracy: 0.7979
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4484 - accuracy: 0.8018
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4322 - accuracy: 0.8096
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4186 - accuracy: 0.8183
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4023 - accuracy: 0.8295
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3869 - accuracy: 0.8403
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3751 - accuracy: 0.8462
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3660 - accuracy: 0.8516
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3593 - accura

In [15]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 101ms/step
[[False]]


In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1510   85]
 [ 195  210]]


0.86

### **Tugas**

In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [19]:
(x_train, y_train), (x_test, y_test)  = tf.keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [20]:
# Preprocess data
x_train = x_train.reshape(x_train.shape[0], -1) / 255.0
x_test = x_test.reshape(x_test.shape[0], -1) / 255.0

In [21]:
ann = tf.keras.models.Sequential()

In [22]:
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))

In [24]:
ann.add(tf.keras.layers.Dense(units=10, activation='softmax'))

In [25]:
ann.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [26]:
# Train the model
ann.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2755 - accuracy: 0.9195 - val_loss: 0.1530 - val_accuracy: 0.9523
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1273 - accuracy: 0.9618 - val_loss: 0.1078 - val_accuracy: 0.9669
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0920 - accuracy: 0.9713 - val_loss: 0.1018 - val_accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0727 - accuracy: 0.9769 - val_loss: 0.0915 - val_accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0589 - accuracy: 0.9810 - val_loss: 0.0886 - val_accuracy: 0.9720


In [27]:
y_pred = ann.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Print the predicted classes and true classes side by side
print(np.concatenate((y_pred_classes.reshape(len(y_pred_classes),1), y_test.reshape(len(y_test),1)),1))


313/313 [==============================] - 1s 2ms/step
[[7 7]
 [2 2]
 [1 1]
 ...
 [4 4]
 [5 5]
 [6 6]]


In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_classes)
print(cm)
accuracy_score(y_test, y_pred_classes)

[[ 963    0    6    1    3    0    1    1    4    1]
 [   0 1128    3    0    0    1    1    0    2    0]
 [   2    2 1012    8    2    0    2    1    3    0]
 [   0    1    4  994    0    2    0    2    4    3]
 [   0    0   10    1  952    0    3    4    1   11]
 [   2    1    0   17    2  857    4    1    5    3]
 [   3    3    4    1    7    6  930    0    3    1]
 [   1    9   19    9    3    0    0  976    1   10]
 [   1    6    7    6    2    3    4    4  937    4]
 [   0    6    2    8    9    3    0    6    4  971]]


0.972